/* ============================================
   pdfGenerators.js — AarogyKendra PDF Reports
   ============================================
   Professional PDF generation using jsPDF +
   jspdf-autotable with AarogyKendra branding.
   
   PDF 1: Regular Checkup Report (Nurse)
   PDF 2: Diagnosis + Prescription Report (Doctor)
   ============================================ */

import jsPDF from 'jspdf';
import 'jspdf-autotable';

// ── Brand Colors ──────────────────────────────
const BRAND = {
  cyan: [34, 211, 238],
  blue: [59, 130, 246],
  dark: [15, 23, 42],
  text: [30, 41, 59],
  muted: [100, 116, 139],
  light: [241, 245, 249],
};

/**
 * Add AarogyKendra branded header to PDF.
 */
function addHeader(doc, title) {
  // Header background
  doc.setFillColor(...BRAND.dark);
  doc.rect(0, 0, 210, 38, 'F');

  // Cyan accent line
  doc.setFillColor(...BRAND.cyan);
  doc.rect(0, 38, 210, 2, 'F');

  // Brand name
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('AarogyKendra', 14, 18);

  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text('AI-Powered Healthcare Management System', 14, 26);

  // Report title
  doc.setFontSize(8);
  doc.setTextColor(...BRAND.cyan);
  doc.text(title.toUpperCase(), 14, 33);

  // Date on right
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  const date = new Date().toLocaleString('en-IN', {
    dateStyle: 'long',
    timeStyle: 'short',
  });
  doc.text(date, 196, 18, { align: 'right' });

  return 48; // Y offset after header
}

/**
 * Add branded footer to PDF.
 */
function addFooter(doc) {
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(7);
  doc.setTextColor(...BRAND.muted);
  doc.text(
    'Generated by AarogyKendra — AI-Powered Healthcare Management | Confidential Medical Record',
    105,
    pageHeight - 10,
    { align: 'center' }
  );
  doc.setDrawColor(...BRAND.cyan);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 16, 196, pageHeight - 16);
}

/**
 * Add a section title with accent line.
 */
function addSectionTitle(doc, title, y) {
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.dark);
  doc.text(title, 14, y);
  doc.setDrawColor(...BRAND.cyan);
  doc.setLineWidth(0.8);
  doc.line(14, y + 2, 60, y + 2);
  return y + 10;
}

/**
 * Add key-value info rows.
 */
function addInfoRow(doc, label, value, y) {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BRAND.muted);
  doc.text(label + ':', 14, y);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...BRAND.text);
  doc.text(String(value || '—'), 60, y);
  return y + 7;
}

// ═══════════════════════════════════════════════
// PDF 1: Regular Checkup Report (Nurse)
// ═══════════════════════════════════════════════
export function generateCheckupPDF(data) {
  const doc = new jsPDF();
  let y = addHeader(doc, 'Regular Checkup Report');

  // Patient Info Section
  y = addSectionTitle(doc, 'Patient Information', y);
  y = addInfoRow(doc, 'Patient Name', data.patientName, y);
  y = addInfoRow(doc, 'Patient ID', data.patientId, y);
  y = addInfoRow(doc, 'Age / Gender', `${data.age || '—'} / ${data.gender || '—'}`, y);
  y = addInfoRow(doc, 'Date & Time', data.dateTime || new Date().toLocaleString('en-IN'), y);
  y = addInfoRow(doc, 'Nurse', data.nurseName || 'Duty Nurse', y);

  y += 5;

  // Vitals Table
  y = addSectionTitle(doc, 'Vital Signs', y);

  doc.autoTable({
    startY: y,
    head: [['Parameter', 'Value', 'Normal Range', 'Status']],
    body: [
      ['Blood Pressure', `${data.bp || '—'} mmHg`, '120/80 mmHg', getBPStatus(data.bp)],
      ['Blood Sugar', `${data.sugar || '—'} mg/dL`, '70-100 mg/dL', getSugarStatus(data.sugar)],
      ['Pulse Rate', `${data.pulse || '—'} bpm`, '60-100 bpm', getPulseStatus(data.pulse)],
      ['Temperature', `${data.temperature || '—'} °F`, '97-99 °F', getTempStatus(data.temperature)],
      ['Weight', `${data.weight || '—'} kg`, '—', 'Recorded'],
    ],
    theme: 'grid',
    headStyles: {
      fillColor: BRAND.dark,
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: 'bold',
    },
    bodyStyles: {
      fontSize: 9,
      textColor: BRAND.text,
    },
    alternateRowStyles: {
      fillColor: BRAND.light,
    },
    margin: { left: 14, right: 14 },
  });

  y = doc.lastAutoTable.finalY + 12;

  // Nurse Notes
  if (data.notes) {
    y = addSectionTitle(doc, 'Nurse Observations', y);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.text);
    const lines = doc.splitTextToSize(data.notes, 180);
    doc.text(lines, 14, y);
  }

  addFooter(doc);

  doc.save(`AarogyKendra_Checkup_${data.patientName || 'Report'}_${Date.now()}.pdf`);
  return doc;
}

// ═══════════════════════════════════════════════
// PDF 2: Diagnosis + Prescription Report (Doctor)
// ═══════════════════════════════════════════════
export function generateDiagnosisPDF(data) {
  const doc = new jsPDF();
  let y = addHeader(doc, 'Diagnosis & Prescription Report');

  // Patient Info
  y = addSectionTitle(doc, 'Patient Information', y);
  y = addInfoRow(doc, 'Patient Name', data.patientName, y);
  y = addInfoRow(doc, 'Patient ID', data.patientId, y);
  y = addInfoRow(doc, 'Age / Gender', `${data.age || '—'} / ${data.gender || '—'}`, y);
  y = addInfoRow(doc, 'Doctor', data.doctorName || 'Attending Physician', y);
  y = addInfoRow(doc, 'Date', data.date || new Date().toLocaleDateString('en-IN'), y);

  y += 5;

  // Diagnosis Section
  y = addSectionTitle(doc, 'Diagnosis', y);
  y = addInfoRow(doc, 'Condition', data.diagnosis, y);
  y = addInfoRow(doc, 'Severity', data.severity || 'Moderate', y);
  y = addInfoRow(doc, 'Status', data.status || 'Confirmed', y);

  if (data.symptoms) {
    y = addInfoRow(doc, 'Symptoms', data.symptoms, y);
  }

  y += 5;

  // Prescription Table
  if (data.medicines && data.medicines.length > 0) {
    y = addSectionTitle(doc, 'Prescription', y);

    doc.autoTable({
      startY: y,
      head: [['#', 'Medicine', 'Dosage', 'Frequency', 'Duration']],
      body: data.medicines.map((med, i) => [
        i + 1,
        med.name || med.medicine || '—',
        med.dosage || '—',
        med.frequency || '—',
        med.duration || '—',
      ]),
      theme: 'grid',
      headStyles: {
        fillColor: BRAND.dark,
        textColor: [255, 255, 255],
        fontSize: 9,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 9,
        textColor: BRAND.text,
      },
      alternateRowStyles: {
        fillColor: BRAND.light,
      },
      margin: { left: 14, right: 14 },
    });

    y = doc.lastAutoTable.finalY + 12;
  }

  // Advice & Follow-up
  if (data.advice) {
    y = addSectionTitle(doc, 'Medical Advice', y);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.text);
    const lines = doc.splitTextToSize(data.advice, 180);
    doc.text(lines, 14, y);
    y += lines.length * 5 + 8;
  }

  if (data.followUp) {
    y = addSectionTitle(doc, 'Follow-up', y);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...BRAND.text);
    doc.text(data.followUp, 14, y);
  }

  addFooter(doc);

  doc.save(`AarogyKendra_Diagnosis_${data.patientName || 'Report'}_${Date.now()}.pdf`);
  return doc;
}

// ── Status Helpers ────────────────────────────
function getBPStatus(bp) {
  if (!bp) return '—';
  const sys = parseInt(bp);
  if (sys > 140) return '⚠ High';
  if (sys < 90) return '⚠ Low';
  return '✓ Normal';
}

function getSugarStatus(sugar) {
  if (!sugar) return '—';
  const val = parseInt(sugar);
  if (val > 140) return '⚠ High';
  if (val < 70) return '⚠ Low';
  return '✓ Normal';
}

function getPulseStatus(pulse) {
  if (!pulse) return '—';
  const val = parseInt(pulse);
  if (val > 100) return '⚠ High';
  if (val < 60) return '⚠ Low';
  return '✓ Normal';
}

function getTempStatus(temp) {
  if (!temp) return '—';
  const val = parseFloat(temp);
  if (val > 99.5) return '⚠ Fever';
  if (val < 96.5) return '⚠ Low';
  return '✓ Normal';
}
